# Generated by Django 3.1.7 on 2021-02-22 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_auto_20210222_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(default=models.CharField(max_length=100, verbose_name='Category Name'), max_length=100, verbose_name='Slug'),
        ),
    ]
